// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: article.sql

package db

import (
	"context"
)

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles (
  content,
  title,
  poster_id
) VALUES (
  $1,
  $2,
  $3
) RETURNING id, poster_id, content, title, created_at
`

type CreateArticleParams struct {
	Content  string `json:"content"`
	Title    string `json:"title"`
	PosterID int64  `json:"poster_id"`
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error) {
	row := q.db.QueryRowContext(ctx, createArticle, arg.Content, arg.Title, arg.PosterID)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.PosterID,
		&i.Content,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}

const deleteArticle = `-- name: DeleteArticle :exec
DELETE FROM articles
WHERE id = $1
`

func (q *Queries) DeleteArticle(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteArticle, id)
	return err
}

const getArticle = `-- name: GetArticle :one
SELECT id, poster_id, content, title, created_at FROM articles
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetArticle(ctx context.Context, id int64) (Article, error) {
	row := q.db.QueryRowContext(ctx, getArticle, id)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.PosterID,
		&i.Content,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}

const listArticles = `-- name: ListArticles :many
SELECT id, poster_id, content, title, created_at FROM articles
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListArticlesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListArticles(ctx context.Context, arg ListArticlesParams) ([]Article, error) {
	rows, err := q.db.QueryContext(ctx, listArticles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.PosterID,
			&i.Content,
			&i.Title,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArticle = `-- name: UpdateArticle :exec
UPDATE articles
SET content = $2,
title = $3
WHERE id = $1
RETURNING id, poster_id, content, title, created_at
`

type UpdateArticleParams struct {
	ID      int64  `json:"id"`
	Content string `json:"content"`
	Title   string `json:"title"`
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) error {
	_, err := q.db.ExecContext(ctx, updateArticle, arg.ID, arg.Content, arg.Title)
	return err
}
